# Generated by Django 4.2 on 2023-06-06 17:39

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, validators=[users.models.validate_birth_date]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                validators=[users.models.validate_email_domain],
            ),
        ),
    ]
