# Generated by Django 4.2 on 2023-06-07 04:18

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_birth_date_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                validators=[users.models.validate_birth_date],
            ),
            preserve_default=False,
        ),
    ]
