# Generated by Django 4.2 on 2023-06-09 06:09

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True, validators=[users.validators.validate_birth_date]
            ),
        ),
    ]
