# Generated by Django 4.2 on 2023-06-06 10:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="slug",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.MaxLengthValidator(10),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="admodel",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="admodel",
            name="price",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
