# Generated by Django 4.2 on 2023-06-13 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0009_alter_categorymodel_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="slug",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
    ]
